### ISSUE TITLE
[Help wanted] - Update for 2 month gap

### ISSUE THREAD

**Issue by chentsulin** [laravel-taiwan/docs#210]
有兩個月沒更新了，希望有餘力的人可以到 [try-update](https://github.com/laravel-taiwan/docs/blob/try-update/views.md) branch 協助排除 CONFLICT，並回報完成

diff: https://github.com/laravel-taiwan/docs/pull/211/files

- [x] CONFLICT (content): Merge conflict in views.md #215 
- [ ] CONFLICT (content): Merge conflict in validation.md #223
- [x] CONFLICT (content): Merge conflict in upgrade.md #217 
- [x] CONFLICT (content): Merge conflict in testing.md #213 
- [x] CONFLICT (content): Merge conflict in routing.md #218 
- [x] CONFLICT (content): Merge conflict in packages.md #219 
- [x] CONFLICT (content): Merge conflict in migrations.md #240 
- [x] CONFLICT (content): Merge conflict in middleware.md #238 
- [x] CONFLICT (content): Merge conflict in installation.md #231 
- [x] CONFLICT (content): Merge conflict in homestead.md #230 
- [x] CONFLICT (content): Merge conflict in eloquent.md #239 
- [x] CONFLICT (content): Merge conflict in eloquent-mutators.md #237 
- [x] CONFLICT (content): Merge conflict in documentation.md #233 
- [x] CONFLICT (content): Merge conflict in contributions.md #235 
- [x] CONFLICT (content): Merge conflict in contracts.md #236 
- [x] CONFLICT (content): Merge conflict in blade.md #232 
- [x] CONFLICT (content): Merge conflict in billing.md #214 
- [x] CONFLICT (content): Merge conflict in authentication.md #212 
- [x] CONFLICT (content): Merge conflict in artisan.md #234

**Comment by jigsawye** [comment]
我昨天跟今天也在試著更新，只是一直無法用指令自動排除，看樣子真要手動來了XD

**Comment by chentsulin** [comment]
這邊有 diff
https://github.com/laravel-taiwan/docs/pull/211/files

**Comment by jigsawye** [comment]
@chentsulin 麻煩 review 一下看這樣對嗎 #212

**Comment by appleboy** [comment]
@jigsawye 看起來ＯＫ

**Comment by jigsawye** [comment]
@appleboy 那我就接著幹了...XD

**Comment by appleboy** [comment]
@jigsawye 處理過的，記得回來把上面的 check list 更新

**Comment by appleboy** [comment]
@jigsawye 我先幫忙把 auth checkbox 打勾並且補上 PR Number。

**Comment by jigsawye** [comment]
@appleboy thanks :+1:

**Comment by neighborhood999** [comment]
Update `validation.md`。再麻煩各位確認一下，怕操作上有錯誤。

**Comment by jigsawye** [comment]
@chentsulin @appleboy 把欠的部分補完了，麻煩有空再幫忙 review
估計 merge 回 5.1 應該也是一片血海...

**Comment by chentsulin** [comment]
done
