### ISSUE TITLE
5.2 文件翻譯進度表

### ISSUE THREAD

**Issue by jigsawye** [laravel-taiwan/docs#287]
[Laravel 中文文件翻譯對照表與規範](https://github.com/laravel-taiwan/docs/issues/259)

翻譯時可以直接在 `5.2` merge 原來的 `5.1` 套用 `5.1` 已翻譯的部分。
翻譯完成在 commit 翻譯的檔案送 PR 即可。
- [x] artisan.md #291 
- [x] authentication.md #320 
- [x] authorization.md #292 
- [x] billing.md #325 
- [x] blade.md
- [x] cache.md #324 
- [x] collections.md
- [x] configuration.md #296 
- [x] container.md #317
- [x] contributions.md
- [x] controllers.md #302 
- [x] database.md
- [x] documentation.md
- [x] elixir.md
- [x] eloquent-collections.md #308 
- [x] eloquent-mutators.md
- [x] eloquent-relationships.md
- [x] eloquent-serialization.md #309 
- [x] eloquent.md #306
- [x] encryption.md
- [x] envoy.md
- [x] errors.md
- [x] events.md #310 
- [x] facades.md
- [x] filesystem.md
- [x] hashing.md
- [x] helpers.md #292 
- [x] homestead.md #297 
- [x] installation.md #298 
- [x] lifecycle.md
- [x] localization.md
- [x] mail.md #292 
- [x] middleware.md #301 
- [x] migrations.md
- [x] packages.md #326 
- [x] pagination.md #305 
- [x] providers.md #305 
- [x] queries.md
- [x] queues.md #328 
- [x] quickstart-intermediate.md #295 
- [x] quickstart.md #294 
- [x] redis.md
- [x] releases.md #293 
- [x] requests.md
- [x] responses.md #303 
- [x] routing.md #300 
- [x] scheduling.md #304 
- [x] seeding.md
- [x] session.md #316
- [x] structure.md #315
- [x] testing.md
- [x] upgrade.md #327 
- [x] validation.md #312 
- [x] views.md #299

**Comment by jigsawye** [comment]
- [ ] `artisan.md`
- [ ] `releases.md`
- [ ] `quickstart-intermediate.md`
- [ ] `quickstart.md`

**Comment by jasteralan** [comment]
translating~
authorization.md
helpers.md 
mail.md

**Comment by appleboy** [comment]
@jasteralan @jigsawye @chentsulin @farrrr 

我先將 default branch 換成 5.2

**Comment by farrrr** [comment]
@appleboy okay... mickey 要開 5.2 的目錄 （還是你已經開好了？ XD)

**Comment by appleboy** [comment]
@farrrr 我去開一下 XD

**Comment by appleboy** [comment]
@farrrr 已經開好了

**Comment by jigsawye** [comment]
@farrrr @appleboy :+1:

**Comment by jigsawye** [comment]
- [ ] `installation.md`
- [ ] `configuration.md`
- [ ] `homestead.md`

**Comment by jigsawye** [comment]
- [ ] `routing.md`
- [ ] `middleware.md`
- [ ] `controller.md`

**Comment by taichunmin** [comment]
[x] views.md #299

**Comment by jigsawye** [comment]
- [ ] `response.md`
- [ ] `upgrade.md`

**Comment by neighborhood999** [comment]
認領之前翻譯過的：
- [ ] eloquent.md
- [ ] eloquent-collections.md
- [ ] eloquent-serialization.md
- [ ] events.md
- [ ] validation.md

**Comment by jasteralan** [comment]
認領
pagination.md
providers.md
scheduling.md

**Comment by odie1111** [comment]
先認一篇
mail.md

**Comment by taichunmin** [comment]
認領 `authentication.md`

**Comment by neighborhood999** [comment]
認領 `cache.md`

**Comment by appleboy** [comment]
這個看起來結束了？要來 5.3 嗎？ＸＤ

**Comment by LouisXXL** [comment]
請問laravel 5.3 已經開始翻了？
